from lib2to3.pygram import python_grammar_no_print_and_exec_statement

import python_rust
import time
import random
from python_rust import sort_string, binary_search, mirror_string, selection_sort, insertion_sort, shell_sort, quick_sort_py

result = sort_string("' ' a '")
print(result)

numbers = random.sample(range(1, 100010000), 2000000)
start = time.time()
selection_sort(numbers)
print(time.time() - start)
start = time.time()
insertion_sort(numbers)
print(time.time() - start)
start = time.time()
shell_sort(numbers)
print(time.time() - start)
start = time.time()
quick_sort_py(numbers)
print(time.time() - start)

print(python_rust.binary_search(12, numbers))

print(mirror_string("Mirrored String"))
print(mirror_string("CN=Keycloak AuthUser,OU=LDAP-Konten,OU=IT-Accounts,DC=ad,DC=grueneerde,DC=com"))

for _x in range(1, 1):
    lst1 = python_rust.LinkedList()
    start = time.time()
    for i in range(1, 1000000):
        lst1.prepend(i)
    lst1.dispose()
    print(time.time() - start)

for _x in range(1, 1):
    start = time.time()
    tree = python_rust.BinaryTree()
    tree.add_value(5)
    tree.add_value(2)
    tree.add_value(8)
    tree.add_value(3)
    tree.add_value(6)
    tree.add_value(1)
    tree.add_value(7)
    tree.add_value(9)
    tree.add_value(4)
    tree.add_value(5)
    tree.add_value(2)
    tree.add_value(8)
    tree.add_value(3)
    tree.add_value(6)
    tree.add_value(1)
    tree.add_value(7)
    tree.add_value(9)
    tree.add_value(4)
    tree.add_value(5)
    tree.add_value(2)
    tree.add_value(8)
    tree.add_value(3)
    tree.add_value(6)
    tree.add_value(1)
    tree.add_value(7)
    tree.add_value(9)
    tree.add_value(4)
    tree.add_value(5)
    tree.add_value(2)
    tree.add_value(8)
    tree.add_value(3)
    tree.add_value(6)
    tree.add_value(1)
    tree.add_value(7)
    tree.add_value(9)
    tree.add_value(4)
    tree.add_value(5)
    tree.add_value(2)
    tree.add_value(8)
    tree.add_value(3)
    tree.add_value(6)
    tree.add_value(1)
    tree.add_value(7)
    tree.add_value(9)
    tree.add_value(4)
    tree.add_value(2)
    tree.add_value(2)
    tree.add_value(8)
    tree.add_value(3)
    tree.add_value(6)
    tree.add_value(1)
    tree.add_value(7)
    tree.add_value(9)
    tree.add_value(4)

    print(tree.contains(100))
    tree.print()
    print(time.time() - start)

morse = python_rust.BinaryMorseTree()

morse.add_value('A', '.-')
morse.add_value('B', '-...')
morse.add_value('C', '-.-.')
morse.add_value('D', '-..')
morse.add_value('E', '.')
morse.add_value('F', '..-.')
morse.add_value('G', '--.')
morse.add_value('H', '....')
morse.add_value('I', '..')
morse.add_value('J', '.---')
morse.add_value('K', '-.-')
morse.add_value('L', '.-..')
morse.add_value('M', '--')
morse.add_value('N', '-.')
morse.add_value('O', '---')
morse.add_value('P', '.--.')
morse.add_value('Q', '--.-')
morse.add_value('R', '.-.')
morse.add_value('S', '...')
morse.add_value('T', '-')
morse.add_value('U', '..-')
morse.add_value('V', '...-')
morse.add_value('W', '.--')
morse.add_value('X', '-..-')
morse.add_value('Y', '-.--')
morse.add_value('Z', '--..')

morse.print()